;;; init-locales.el --- Configure default local -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-Consolas-bold-normal-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 14.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline--normal-normal-normal-mono-*-*-*-*-c-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 16.5)))

(setq initial-scratch-message "")

(provide 'init-local)
;;; init-locales.el ends here
